//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex.MobileHub.Devel.DevelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevelService.DevelopersSoap")]
    public interface DevelopersSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppGetTableDefinition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        Plex.MobileHub.Devel.DevelService.TableDefinition[] AppGetTableDefinition(int nAppId, string sAppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AppGetTableDefinition", ReplyAction="*")]
        System.IAsyncResult BeginAppGetTableDefinition(int nAppId, string sAppAuthKey, System.AsyncCallback callback, object asyncState);
        
        Plex.MobileHub.Devel.DevelService.TableDefinition[] EndAppGetTableDefinition(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AppGetQueries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        Plex.MobileHub.Devel.DevelService.QueryDefinition[] AppGetQueries(int AppId, string AppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AppGetQueries", ReplyAction="*")]
        System.IAsyncResult BeginAppGetQueries(int AppId, string AppAuthKey, System.AsyncCallback callback, object asyncState);
        
        Plex.MobileHub.Devel.DevelService.QueryDefinition[] EndAppGetQueries(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClientGetDatabaseList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        void ClientGetDatabaseList(int nClientId, int nAppId);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ClientGetDatabaseList", ReplyAction="*")]
        System.IAsyncResult BeginClientGetDatabaseList(int nClientId, int nAppId, System.AsyncCallback callback, object asyncState);
        
        void EndClientGetDatabaseList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QryCreateOffTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        bool QryCreateOffTable(int AppId, string Auth, int TableId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/QryCreateOffTable", ReplyAction="*")]
        System.IAsyncResult BeginQryCreateOffTable(int AppId, string Auth, int TableId, string QueryName, System.AsyncCallback callback, object asyncState);
        
        bool EndQryCreateOffTable(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QryCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        bool QryCreate(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/QryCreate", ReplyAction="*")]
        System.IAsyncResult BeginQryCreate(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query, System.AsyncCallback callback, object asyncState);
        
        bool EndQryCreate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QryDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/QryDelete", ReplyAction="*")]
        System.IAsyncResult BeginQryDelete(int nAppId, string sAppAuthKey, string sQueryName, System.AsyncCallback callback, object asyncState);
        
        bool EndQryDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppSyncData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        Plex.MobileHub.Devel.DevelService.DevelSyncData GetAppSyncData(int AppId, string AppKey);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAppSyncData", ReplyAction="*")]
        System.IAsyncResult BeginGetAppSyncData(int AppId, string AppKey, System.AsyncCallback callback, object asyncState);
        
        Plex.MobileHub.Devel.DevelService.DevelSyncData EndGetAppSyncData(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TableDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private bool allowInsertField;
        
        private bool allowDeleteField;
        
        private bool allowUpdateField;
        
        private bool allowQueryField;
        
        private Column[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool AllowInsert {
            get {
                return this.allowInsertField;
            }
            set {
                this.allowInsertField = value;
                this.RaisePropertyChanged("AllowInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool AllowDelete {
            get {
                return this.allowDeleteField;
            }
            set {
                this.allowDeleteField = value;
                this.RaisePropertyChanged("AllowDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool AllowUpdate {
            get {
                return this.allowUpdateField;
            }
            set {
                this.allowUpdateField = value;
                this.RaisePropertyChanged("AllowUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool AllowQuery {
            get {
                return this.allowQueryField;
            }
            set {
                this.allowQueryField = value;
                this.RaisePropertyChanged("AllowQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Column[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Column : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private System.Nullable<int> columnSequenceField;
        
        private string dataTypeField;
        
        private System.Nullable<int> dataLengthField;
        
        private System.Nullable<int> dataPrecisionField;
        
        private System.Nullable<int> dataScaleField;
        
        private System.Nullable<bool> allowDbNullField;
        
        private System.Nullable<bool> isReadOnlyField;
        
        private System.Nullable<bool> isLongField;
        
        private System.Nullable<bool> isKeyField;
        
        private string keyTypeField;
        
        private System.Nullable<bool> isUniqueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ColumnSequence {
            get {
                return this.columnSequenceField;
            }
            set {
                this.columnSequenceField = value;
                this.RaisePropertyChanged("ColumnSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DataPrecision {
            get {
                return this.dataPrecisionField;
            }
            set {
                this.dataPrecisionField = value;
                this.RaisePropertyChanged("DataPrecision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DataScale {
            get {
                return this.dataScaleField;
            }
            set {
                this.dataScaleField = value;
                this.RaisePropertyChanged("DataScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> AllowDbNull {
            get {
                return this.allowDbNullField;
            }
            set {
                this.allowDbNullField = value;
                this.RaisePropertyChanged("AllowDbNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
                this.RaisePropertyChanged("IsLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsKey {
            get {
                return this.isKeyField;
            }
            set {
                this.isKeyField = value;
                this.RaisePropertyChanged("IsKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> IsUnique {
            get {
                return this.isUniqueField;
            }
            set {
                this.isUniqueField = value;
                this.RaisePropertyChanged("IsUnique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_QUERIES))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_TABLES))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_USER_TYPES))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_TABLE_COLUMNS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_QUERY_COLUMNS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_QUERY_CONDITIONS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APPS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class PlexxisDataTransferObjects : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] primaryKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] PrimaryKey {
            get {
                return this.primaryKeyField;
            }
            set {
                this.primaryKeyField = value;
                this.RaisePropertyChanged("PrimaryKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_QUERIES : PlexxisDataTransferObjects {
        
        private int qUERY_IDField;
        
        private int aPP_IDField;
        
        private string nAMEField;
        
        private string tABLE_NAMEField;
        
        private string dESCRIPTIONField;
        
        private int tABLE_IDField;
        
        private int iS_DELTAField;
        
        private string sQLField;
        
        private System.Nullable<int> sEQ_LIMIT_TIMESPANField;
        
        private System.Nullable<int> sEQ_LIMITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int QUERY_ID {
            get {
                return this.qUERY_IDField;
            }
            set {
                this.qUERY_IDField = value;
                this.RaisePropertyChanged("QUERY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TABLE_NAME {
            get {
                return this.tABLE_NAMEField;
            }
            set {
                this.tABLE_NAMEField = value;
                this.RaisePropertyChanged("TABLE_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int TABLE_ID {
            get {
                return this.tABLE_IDField;
            }
            set {
                this.tABLE_IDField = value;
                this.RaisePropertyChanged("TABLE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int IS_DELTA {
            get {
                return this.iS_DELTAField;
            }
            set {
                this.iS_DELTAField = value;
                this.RaisePropertyChanged("IS_DELTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SQL {
            get {
                return this.sQLField;
            }
            set {
                this.sQLField = value;
                this.RaisePropertyChanged("SQL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> SEQ_LIMIT_TIMESPAN {
            get {
                return this.sEQ_LIMIT_TIMESPANField;
            }
            set {
                this.sEQ_LIMIT_TIMESPANField = value;
                this.RaisePropertyChanged("SEQ_LIMIT_TIMESPAN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> SEQ_LIMIT {
            get {
                return this.sEQ_LIMITField;
            }
            set {
                this.sEQ_LIMITField = value;
                this.RaisePropertyChanged("SEQ_LIMIT");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_TABLES : PlexxisDataTransferObjects {
        
        private int tABLE_IDField;
        
        private int aPP_IDField;
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private int iNSERT_ALLOWEDField;
        
        private int uPDATE_ALLOWEDField;
        
        private int dELETE_ALLOWEDField;
        
        private int qUERY_ALLOWEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TABLE_ID {
            get {
                return this.tABLE_IDField;
            }
            set {
                this.tABLE_IDField = value;
                this.RaisePropertyChanged("TABLE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int INSERT_ALLOWED {
            get {
                return this.iNSERT_ALLOWEDField;
            }
            set {
                this.iNSERT_ALLOWEDField = value;
                this.RaisePropertyChanged("INSERT_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UPDATE_ALLOWED {
            get {
                return this.uPDATE_ALLOWEDField;
            }
            set {
                this.uPDATE_ALLOWEDField = value;
                this.RaisePropertyChanged("UPDATE_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DELETE_ALLOWED {
            get {
                return this.dELETE_ALLOWEDField;
            }
            set {
                this.dELETE_ALLOWEDField = value;
                this.RaisePropertyChanged("DELETE_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int QUERY_ALLOWED {
            get {
                return this.qUERY_ALLOWEDField;
            }
            set {
                this.qUERY_ALLOWEDField = value;
                this.RaisePropertyChanged("QUERY_ALLOWED");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_USER_TYPES : PlexxisDataTransferObjects {
        
        private int uSER_TYPE_IDField;
        
        private int aPP_IDField;
        
        private string cODEField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int USER_TYPE_ID {
            get {
                return this.uSER_TYPE_IDField;
            }
            set {
                this.uSER_TYPE_IDField = value;
                this.RaisePropertyChanged("USER_TYPE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
                this.RaisePropertyChanged("CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_TABLE_COLUMNS : PlexxisDataTransferObjects {
        
        private int tABLE_IDField;
        
        private int tABLE_COLUMN_IDField;
        
        private string cOLUMN_NAMEField;
        
        private int cOLUMN_SEQUENCEField;
        
        private string dATA_TYPEField;
        
        private System.Nullable<int> dATA_LENGTHField;
        
        private System.Nullable<int> dATA_PRECISIONField;
        
        private System.Nullable<int> dATA_SCALEField;
        
        private System.Nullable<int> aLLOW_DB_NULLField;
        
        private System.Nullable<int> iS_READ_ONLYField;
        
        private System.Nullable<int> iS_LONGField;
        
        private System.Nullable<int> iS_KEYField;
        
        private string kEY_TYPEField;
        
        private System.Nullable<int> iS_UNIQUEField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TABLE_ID {
            get {
                return this.tABLE_IDField;
            }
            set {
                this.tABLE_IDField = value;
                this.RaisePropertyChanged("TABLE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TABLE_COLUMN_ID {
            get {
                return this.tABLE_COLUMN_IDField;
            }
            set {
                this.tABLE_COLUMN_IDField = value;
                this.RaisePropertyChanged("TABLE_COLUMN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COLUMN_NAME {
            get {
                return this.cOLUMN_NAMEField;
            }
            set {
                this.cOLUMN_NAMEField = value;
                this.RaisePropertyChanged("COLUMN_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int COLUMN_SEQUENCE {
            get {
                return this.cOLUMN_SEQUENCEField;
            }
            set {
                this.cOLUMN_SEQUENCEField = value;
                this.RaisePropertyChanged("COLUMN_SEQUENCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DATA_TYPE {
            get {
                return this.dATA_TYPEField;
            }
            set {
                this.dATA_TYPEField = value;
                this.RaisePropertyChanged("DATA_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DATA_LENGTH {
            get {
                return this.dATA_LENGTHField;
            }
            set {
                this.dATA_LENGTHField = value;
                this.RaisePropertyChanged("DATA_LENGTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> DATA_PRECISION {
            get {
                return this.dATA_PRECISIONField;
            }
            set {
                this.dATA_PRECISIONField = value;
                this.RaisePropertyChanged("DATA_PRECISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> DATA_SCALE {
            get {
                return this.dATA_SCALEField;
            }
            set {
                this.dATA_SCALEField = value;
                this.RaisePropertyChanged("DATA_SCALE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> ALLOW_DB_NULL {
            get {
                return this.aLLOW_DB_NULLField;
            }
            set {
                this.aLLOW_DB_NULLField = value;
                this.RaisePropertyChanged("ALLOW_DB_NULL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> IS_READ_ONLY {
            get {
                return this.iS_READ_ONLYField;
            }
            set {
                this.iS_READ_ONLYField = value;
                this.RaisePropertyChanged("IS_READ_ONLY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> IS_LONG {
            get {
                return this.iS_LONGField;
            }
            set {
                this.iS_LONGField = value;
                this.RaisePropertyChanged("IS_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> IS_KEY {
            get {
                return this.iS_KEYField;
            }
            set {
                this.iS_KEYField = value;
                this.RaisePropertyChanged("IS_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string KEY_TYPE {
            get {
                return this.kEY_TYPEField;
            }
            set {
                this.kEY_TYPEField = value;
                this.RaisePropertyChanged("KEY_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> IS_UNIQUE {
            get {
                return this.iS_UNIQUEField;
            }
            set {
                this.iS_UNIQUEField = value;
                this.RaisePropertyChanged("IS_UNIQUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_QUERY_COLUMNS : PlexxisDataTransferObjects {
        
        private int cOLUMN_IDField;
        
        private int qUERY_IDField;
        
        private string cOLUMN_NAMEField;
        
        private int cOLUMN_SEQUENCEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int COLUMN_ID {
            get {
                return this.cOLUMN_IDField;
            }
            set {
                this.cOLUMN_IDField = value;
                this.RaisePropertyChanged("COLUMN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int QUERY_ID {
            get {
                return this.qUERY_IDField;
            }
            set {
                this.qUERY_IDField = value;
                this.RaisePropertyChanged("QUERY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COLUMN_NAME {
            get {
                return this.cOLUMN_NAMEField;
            }
            set {
                this.cOLUMN_NAMEField = value;
                this.RaisePropertyChanged("COLUMN_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int COLUMN_SEQUENCE {
            get {
                return this.cOLUMN_SEQUENCEField;
            }
            set {
                this.cOLUMN_SEQUENCEField = value;
                this.RaisePropertyChanged("COLUMN_SEQUENCE");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APP_QUERY_CONDITIONS : PlexxisDataTransferObjects {
        
        private int cONDITION_IDField;
        
        private int qUERY_IDField;
        
        private string cOLUMN_NAMEField;
        
        private string cOLUMN_NVLField;
        
        private string cOLUMN_VALUEField;
        
        private string oPERATORField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CONDITION_ID {
            get {
                return this.cONDITION_IDField;
            }
            set {
                this.cONDITION_IDField = value;
                this.RaisePropertyChanged("CONDITION_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int QUERY_ID {
            get {
                return this.qUERY_IDField;
            }
            set {
                this.qUERY_IDField = value;
                this.RaisePropertyChanged("QUERY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COLUMN_NAME {
            get {
                return this.cOLUMN_NAMEField;
            }
            set {
                this.cOLUMN_NAMEField = value;
                this.RaisePropertyChanged("COLUMN_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string COLUMN_NVL {
            get {
                return this.cOLUMN_NVLField;
            }
            set {
                this.cOLUMN_NVLField = value;
                this.RaisePropertyChanged("COLUMN_NVL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string COLUMN_VALUE {
            get {
                return this.cOLUMN_VALUEField;
            }
            set {
                this.cOLUMN_VALUEField = value;
                this.RaisePropertyChanged("COLUMN_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OPERATOR {
            get {
                return this.oPERATORField;
            }
            set {
                this.oPERATORField = value;
                this.RaisePropertyChanged("OPERATOR");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class APPS : PlexxisDataTransferObjects {
        
        private int aPP_IDField;
        
        private string aUTH_KEYField;
        
        private string tITLEField;
        
        private string dESCRIPTIONField;
        
        private int iS_CLIENT_CUSTOM_APPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AUTH_KEY {
            get {
                return this.aUTH_KEYField;
            }
            set {
                this.aUTH_KEYField = value;
                this.RaisePropertyChanged("AUTH_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
                this.RaisePropertyChanged("TITLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IS_CLIENT_CUSTOM_APP {
            get {
                return this.iS_CLIENT_CUSTOM_APPField;
            }
            set {
                this.iS_CLIENT_CUSTOM_APPField = value;
                this.RaisePropertyChanged("IS_CLIENT_CUSTOM_APP");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DevelSyncData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APPS appField;
        
        private APP_QUERIES[] appQueriesField;
        
        private APP_TABLES[] appTablesField;
        
        private APP_USER_TYPES[] appUserTypesField;
        
        private APP_TABLE_COLUMNS[] appTabColumnsField;
        
        private APP_QUERY_COLUMNS[] appQryColumnsField;
        
        private APP_QUERY_CONDITIONS[] appQryConditionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APPS App {
            get {
                return this.appField;
            }
            set {
                this.appField = value;
                this.RaisePropertyChanged("App");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public APP_QUERIES[] AppQueries {
            get {
                return this.appQueriesField;
            }
            set {
                this.appQueriesField = value;
                this.RaisePropertyChanged("AppQueries");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public APP_TABLES[] AppTables {
            get {
                return this.appTablesField;
            }
            set {
                this.appTablesField = value;
                this.RaisePropertyChanged("AppTables");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public APP_USER_TYPES[] AppUserTypes {
            get {
                return this.appUserTypesField;
            }
            set {
                this.appUserTypesField = value;
                this.RaisePropertyChanged("AppUserTypes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public APP_TABLE_COLUMNS[] AppTabColumns {
            get {
                return this.appTabColumnsField;
            }
            set {
                this.appTabColumnsField = value;
                this.RaisePropertyChanged("AppTabColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public APP_QUERY_COLUMNS[] AppQryColumns {
            get {
                return this.appQryColumnsField;
            }
            set {
                this.appQryColumnsField = value;
                this.RaisePropertyChanged("AppQryColumns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public APP_QUERY_CONDITIONS[] AppQryConditions {
            get {
                return this.appQryConditionsField;
            }
            set {
                this.appQryConditionsField = value;
                this.RaisePropertyChanged("AppQryConditions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Condition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private string columnNVLField;
        
        private string columnValueField;
        
        private string operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ColumnNVL {
            get {
                return this.columnNVLField;
            }
            set {
                this.columnNVLField = value;
                this.RaisePropertyChanged("ColumnNVL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ColumnValue {
            get {
                return this.columnValueField;
            }
            set {
                this.columnValueField = value;
                this.RaisePropertyChanged("ColumnValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class QueryDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryNameField;
        
        private string tableNameField;
        
        private bool trackDeltaField;
        
        private string[] columnNamesField;
        
        private Condition[] whereClausesField;
        
        private string sqlField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QueryName {
            get {
                return this.queryNameField;
            }
            set {
                this.queryNameField = value;
                this.RaisePropertyChanged("QueryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool TrackDelta {
            get {
                return this.trackDeltaField;
            }
            set {
                this.trackDeltaField = value;
                this.RaisePropertyChanged("TrackDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] ColumnNames {
            get {
                return this.columnNamesField;
            }
            set {
                this.columnNamesField = value;
                this.RaisePropertyChanged("ColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Condition[] WhereClauses {
            get {
                return this.whereClausesField;
            }
            set {
                this.whereClausesField = value;
                this.RaisePropertyChanged("WhereClauses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
                this.RaisePropertyChanged("Sql");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DevelopersSoapChannel : Plex.MobileHub.Devel.DevelService.DevelopersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppGetTableDefinitionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AppGetTableDefinitionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Plex.MobileHub.Devel.DevelService.TableDefinition[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Plex.MobileHub.Devel.DevelService.TableDefinition[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppGetQueriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AppGetQueriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Plex.MobileHub.Devel.DevelService.QueryDefinition[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Plex.MobileHub.Devel.DevelService.QueryDefinition[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QryCreateOffTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QryCreateOffTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QryCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QryCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QryDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public QryDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAppSyncDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAppSyncDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Plex.MobileHub.Devel.DevelService.DevelSyncData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Plex.MobileHub.Devel.DevelService.DevelSyncData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevelopersSoapClient : System.ServiceModel.ClientBase<Plex.MobileHub.Devel.DevelService.DevelopersSoap>, Plex.MobileHub.Devel.DevelService.DevelopersSoap {
        
        private BeginOperationDelegate onBeginAppGetTableDefinitionDelegate;
        
        private EndOperationDelegate onEndAppGetTableDefinitionDelegate;
        
        private System.Threading.SendOrPostCallback onAppGetTableDefinitionCompletedDelegate;
        
        private BeginOperationDelegate onBeginAppGetQueriesDelegate;
        
        private EndOperationDelegate onEndAppGetQueriesDelegate;
        
        private System.Threading.SendOrPostCallback onAppGetQueriesCompletedDelegate;
        
        private BeginOperationDelegate onBeginClientGetDatabaseListDelegate;
        
        private EndOperationDelegate onEndClientGetDatabaseListDelegate;
        
        private System.Threading.SendOrPostCallback onClientGetDatabaseListCompletedDelegate;
        
        private BeginOperationDelegate onBeginQryCreateOffTableDelegate;
        
        private EndOperationDelegate onEndQryCreateOffTableDelegate;
        
        private System.Threading.SendOrPostCallback onQryCreateOffTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginQryCreateDelegate;
        
        private EndOperationDelegate onEndQryCreateDelegate;
        
        private System.Threading.SendOrPostCallback onQryCreateCompletedDelegate;
        
        private BeginOperationDelegate onBeginQryDeleteDelegate;
        
        private EndOperationDelegate onEndQryDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onQryDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAppSyncDataDelegate;
        
        private EndOperationDelegate onEndGetAppSyncDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetAppSyncDataCompletedDelegate;
        
        public DevelopersSoapClient() {
        }
        
        public DevelopersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevelopersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevelopersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevelopersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<AppGetTableDefinitionCompletedEventArgs> AppGetTableDefinitionCompleted;
        
        public event System.EventHandler<AppGetQueriesCompletedEventArgs> AppGetQueriesCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ClientGetDatabaseListCompleted;
        
        public event System.EventHandler<QryCreateOffTableCompletedEventArgs> QryCreateOffTableCompleted;
        
        public event System.EventHandler<QryCreateCompletedEventArgs> QryCreateCompleted;
        
        public event System.EventHandler<QryDeleteCompletedEventArgs> QryDeleteCompleted;
        
        public event System.EventHandler<GetAppSyncDataCompletedEventArgs> GetAppSyncDataCompleted;
        
        public Plex.MobileHub.Devel.DevelService.TableDefinition[] AppGetTableDefinition(int nAppId, string sAppAuthKey) {
            return base.Channel.AppGetTableDefinition(nAppId, sAppAuthKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAppGetTableDefinition(int nAppId, string sAppAuthKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAppGetTableDefinition(nAppId, sAppAuthKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Plex.MobileHub.Devel.DevelService.TableDefinition[] EndAppGetTableDefinition(System.IAsyncResult result) {
            return base.Channel.EndAppGetTableDefinition(result);
        }
        
        private System.IAsyncResult OnBeginAppGetTableDefinition(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int nAppId = ((int)(inValues[0]));
            string sAppAuthKey = ((string)(inValues[1]));
            return this.BeginAppGetTableDefinition(nAppId, sAppAuthKey, callback, asyncState);
        }
        
        private object[] OnEndAppGetTableDefinition(System.IAsyncResult result) {
            Plex.MobileHub.Devel.DevelService.TableDefinition[] retVal = this.EndAppGetTableDefinition(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAppGetTableDefinitionCompleted(object state) {
            if ((this.AppGetTableDefinitionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AppGetTableDefinitionCompleted(this, new AppGetTableDefinitionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AppGetTableDefinitionAsync(int nAppId, string sAppAuthKey) {
            this.AppGetTableDefinitionAsync(nAppId, sAppAuthKey, null);
        }
        
        public void AppGetTableDefinitionAsync(int nAppId, string sAppAuthKey, object userState) {
            if ((this.onBeginAppGetTableDefinitionDelegate == null)) {
                this.onBeginAppGetTableDefinitionDelegate = new BeginOperationDelegate(this.OnBeginAppGetTableDefinition);
            }
            if ((this.onEndAppGetTableDefinitionDelegate == null)) {
                this.onEndAppGetTableDefinitionDelegate = new EndOperationDelegate(this.OnEndAppGetTableDefinition);
            }
            if ((this.onAppGetTableDefinitionCompletedDelegate == null)) {
                this.onAppGetTableDefinitionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAppGetTableDefinitionCompleted);
            }
            base.InvokeAsync(this.onBeginAppGetTableDefinitionDelegate, new object[] {
                        nAppId,
                        sAppAuthKey}, this.onEndAppGetTableDefinitionDelegate, this.onAppGetTableDefinitionCompletedDelegate, userState);
        }
        
        public Plex.MobileHub.Devel.DevelService.QueryDefinition[] AppGetQueries(int AppId, string AppAuthKey) {
            return base.Channel.AppGetQueries(AppId, AppAuthKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginAppGetQueries(int AppId, string AppAuthKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAppGetQueries(AppId, AppAuthKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Plex.MobileHub.Devel.DevelService.QueryDefinition[] EndAppGetQueries(System.IAsyncResult result) {
            return base.Channel.EndAppGetQueries(result);
        }
        
        private System.IAsyncResult OnBeginAppGetQueries(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int AppId = ((int)(inValues[0]));
            string AppAuthKey = ((string)(inValues[1]));
            return this.BeginAppGetQueries(AppId, AppAuthKey, callback, asyncState);
        }
        
        private object[] OnEndAppGetQueries(System.IAsyncResult result) {
            Plex.MobileHub.Devel.DevelService.QueryDefinition[] retVal = this.EndAppGetQueries(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAppGetQueriesCompleted(object state) {
            if ((this.AppGetQueriesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AppGetQueriesCompleted(this, new AppGetQueriesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AppGetQueriesAsync(int AppId, string AppAuthKey) {
            this.AppGetQueriesAsync(AppId, AppAuthKey, null);
        }
        
        public void AppGetQueriesAsync(int AppId, string AppAuthKey, object userState) {
            if ((this.onBeginAppGetQueriesDelegate == null)) {
                this.onBeginAppGetQueriesDelegate = new BeginOperationDelegate(this.OnBeginAppGetQueries);
            }
            if ((this.onEndAppGetQueriesDelegate == null)) {
                this.onEndAppGetQueriesDelegate = new EndOperationDelegate(this.OnEndAppGetQueries);
            }
            if ((this.onAppGetQueriesCompletedDelegate == null)) {
                this.onAppGetQueriesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAppGetQueriesCompleted);
            }
            base.InvokeAsync(this.onBeginAppGetQueriesDelegate, new object[] {
                        AppId,
                        AppAuthKey}, this.onEndAppGetQueriesDelegate, this.onAppGetQueriesCompletedDelegate, userState);
        }
        
        public void ClientGetDatabaseList(int nClientId, int nAppId) {
            base.Channel.ClientGetDatabaseList(nClientId, nAppId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginClientGetDatabaseList(int nClientId, int nAppId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginClientGetDatabaseList(nClientId, nAppId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndClientGetDatabaseList(System.IAsyncResult result) {
            base.Channel.EndClientGetDatabaseList(result);
        }
        
        private System.IAsyncResult OnBeginClientGetDatabaseList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int nClientId = ((int)(inValues[0]));
            int nAppId = ((int)(inValues[1]));
            return this.BeginClientGetDatabaseList(nClientId, nAppId, callback, asyncState);
        }
        
        private object[] OnEndClientGetDatabaseList(System.IAsyncResult result) {
            this.EndClientGetDatabaseList(result);
            return null;
        }
        
        private void OnClientGetDatabaseListCompleted(object state) {
            if ((this.ClientGetDatabaseListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ClientGetDatabaseListCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ClientGetDatabaseListAsync(int nClientId, int nAppId) {
            this.ClientGetDatabaseListAsync(nClientId, nAppId, null);
        }
        
        public void ClientGetDatabaseListAsync(int nClientId, int nAppId, object userState) {
            if ((this.onBeginClientGetDatabaseListDelegate == null)) {
                this.onBeginClientGetDatabaseListDelegate = new BeginOperationDelegate(this.OnBeginClientGetDatabaseList);
            }
            if ((this.onEndClientGetDatabaseListDelegate == null)) {
                this.onEndClientGetDatabaseListDelegate = new EndOperationDelegate(this.OnEndClientGetDatabaseList);
            }
            if ((this.onClientGetDatabaseListCompletedDelegate == null)) {
                this.onClientGetDatabaseListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnClientGetDatabaseListCompleted);
            }
            base.InvokeAsync(this.onBeginClientGetDatabaseListDelegate, new object[] {
                        nClientId,
                        nAppId}, this.onEndClientGetDatabaseListDelegate, this.onClientGetDatabaseListCompletedDelegate, userState);
        }
        
        public bool QryCreateOffTable(int AppId, string Auth, int TableId, string QueryName) {
            return base.Channel.QryCreateOffTable(AppId, Auth, TableId, QueryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQryCreateOffTable(int AppId, string Auth, int TableId, string QueryName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQryCreateOffTable(AppId, Auth, TableId, QueryName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndQryCreateOffTable(System.IAsyncResult result) {
            return base.Channel.EndQryCreateOffTable(result);
        }
        
        private System.IAsyncResult OnBeginQryCreateOffTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int AppId = ((int)(inValues[0]));
            string Auth = ((string)(inValues[1]));
            int TableId = ((int)(inValues[2]));
            string QueryName = ((string)(inValues[3]));
            return this.BeginQryCreateOffTable(AppId, Auth, TableId, QueryName, callback, asyncState);
        }
        
        private object[] OnEndQryCreateOffTable(System.IAsyncResult result) {
            bool retVal = this.EndQryCreateOffTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQryCreateOffTableCompleted(object state) {
            if ((this.QryCreateOffTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QryCreateOffTableCompleted(this, new QryCreateOffTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QryCreateOffTableAsync(int AppId, string Auth, int TableId, string QueryName) {
            this.QryCreateOffTableAsync(AppId, Auth, TableId, QueryName, null);
        }
        
        public void QryCreateOffTableAsync(int AppId, string Auth, int TableId, string QueryName, object userState) {
            if ((this.onBeginQryCreateOffTableDelegate == null)) {
                this.onBeginQryCreateOffTableDelegate = new BeginOperationDelegate(this.OnBeginQryCreateOffTable);
            }
            if ((this.onEndQryCreateOffTableDelegate == null)) {
                this.onEndQryCreateOffTableDelegate = new EndOperationDelegate(this.OnEndQryCreateOffTable);
            }
            if ((this.onQryCreateOffTableCompletedDelegate == null)) {
                this.onQryCreateOffTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQryCreateOffTableCompleted);
            }
            base.InvokeAsync(this.onBeginQryCreateOffTableDelegate, new object[] {
                        AppId,
                        Auth,
                        TableId,
                        QueryName}, this.onEndQryCreateOffTableDelegate, this.onQryCreateOffTableCompletedDelegate, userState);
        }
        
        public bool QryCreate(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query) {
            return base.Channel.QryCreate(nAppId, sAppAuthKey, Query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQryCreate(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQryCreate(nAppId, sAppAuthKey, Query, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndQryCreate(System.IAsyncResult result) {
            return base.Channel.EndQryCreate(result);
        }
        
        private System.IAsyncResult OnBeginQryCreate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int nAppId = ((int)(inValues[0]));
            string sAppAuthKey = ((string)(inValues[1]));
            Plex.MobileHub.Devel.DevelService.QueryDefinition Query = ((Plex.MobileHub.Devel.DevelService.QueryDefinition)(inValues[2]));
            return this.BeginQryCreate(nAppId, sAppAuthKey, Query, callback, asyncState);
        }
        
        private object[] OnEndQryCreate(System.IAsyncResult result) {
            bool retVal = this.EndQryCreate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQryCreateCompleted(object state) {
            if ((this.QryCreateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QryCreateCompleted(this, new QryCreateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QryCreateAsync(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query) {
            this.QryCreateAsync(nAppId, sAppAuthKey, Query, null);
        }
        
        public void QryCreateAsync(int nAppId, string sAppAuthKey, Plex.MobileHub.Devel.DevelService.QueryDefinition Query, object userState) {
            if ((this.onBeginQryCreateDelegate == null)) {
                this.onBeginQryCreateDelegate = new BeginOperationDelegate(this.OnBeginQryCreate);
            }
            if ((this.onEndQryCreateDelegate == null)) {
                this.onEndQryCreateDelegate = new EndOperationDelegate(this.OnEndQryCreate);
            }
            if ((this.onQryCreateCompletedDelegate == null)) {
                this.onQryCreateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQryCreateCompleted);
            }
            base.InvokeAsync(this.onBeginQryCreateDelegate, new object[] {
                        nAppId,
                        sAppAuthKey,
                        Query}, this.onEndQryCreateDelegate, this.onQryCreateCompletedDelegate, userState);
        }
        
        public bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName) {
            return base.Channel.QryDelete(nAppId, sAppAuthKey, sQueryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginQryDelete(int nAppId, string sAppAuthKey, string sQueryName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginQryDelete(nAppId, sAppAuthKey, sQueryName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public bool EndQryDelete(System.IAsyncResult result) {
            return base.Channel.EndQryDelete(result);
        }
        
        private System.IAsyncResult OnBeginQryDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int nAppId = ((int)(inValues[0]));
            string sAppAuthKey = ((string)(inValues[1]));
            string sQueryName = ((string)(inValues[2]));
            return this.BeginQryDelete(nAppId, sAppAuthKey, sQueryName, callback, asyncState);
        }
        
        private object[] OnEndQryDelete(System.IAsyncResult result) {
            bool retVal = this.EndQryDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnQryDeleteCompleted(object state) {
            if ((this.QryDeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.QryDeleteCompleted(this, new QryDeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName) {
            this.QryDeleteAsync(nAppId, sAppAuthKey, sQueryName, null);
        }
        
        public void QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName, object userState) {
            if ((this.onBeginQryDeleteDelegate == null)) {
                this.onBeginQryDeleteDelegate = new BeginOperationDelegate(this.OnBeginQryDelete);
            }
            if ((this.onEndQryDeleteDelegate == null)) {
                this.onEndQryDeleteDelegate = new EndOperationDelegate(this.OnEndQryDelete);
            }
            if ((this.onQryDeleteCompletedDelegate == null)) {
                this.onQryDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnQryDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginQryDeleteDelegate, new object[] {
                        nAppId,
                        sAppAuthKey,
                        sQueryName}, this.onEndQryDeleteDelegate, this.onQryDeleteCompletedDelegate, userState);
        }
        
        public Plex.MobileHub.Devel.DevelService.DevelSyncData GetAppSyncData(int AppId, string AppKey) {
            return base.Channel.GetAppSyncData(AppId, AppKey);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAppSyncData(int AppId, string AppKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAppSyncData(AppId, AppKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Plex.MobileHub.Devel.DevelService.DevelSyncData EndGetAppSyncData(System.IAsyncResult result) {
            return base.Channel.EndGetAppSyncData(result);
        }
        
        private System.IAsyncResult OnBeginGetAppSyncData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int AppId = ((int)(inValues[0]));
            string AppKey = ((string)(inValues[1]));
            return this.BeginGetAppSyncData(AppId, AppKey, callback, asyncState);
        }
        
        private object[] OnEndGetAppSyncData(System.IAsyncResult result) {
            Plex.MobileHub.Devel.DevelService.DevelSyncData retVal = this.EndGetAppSyncData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAppSyncDataCompleted(object state) {
            if ((this.GetAppSyncDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAppSyncDataCompleted(this, new GetAppSyncDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAppSyncDataAsync(int AppId, string AppKey) {
            this.GetAppSyncDataAsync(AppId, AppKey, null);
        }
        
        public void GetAppSyncDataAsync(int AppId, string AppKey, object userState) {
            if ((this.onBeginGetAppSyncDataDelegate == null)) {
                this.onBeginGetAppSyncDataDelegate = new BeginOperationDelegate(this.OnBeginGetAppSyncData);
            }
            if ((this.onEndGetAppSyncDataDelegate == null)) {
                this.onEndGetAppSyncDataDelegate = new EndOperationDelegate(this.OnEndGetAppSyncData);
            }
            if ((this.onGetAppSyncDataCompletedDelegate == null)) {
                this.onGetAppSyncDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAppSyncDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetAppSyncDataDelegate, new object[] {
                        AppId,
                        AppKey}, this.onEndGetAppSyncDataDelegate, this.onGetAppSyncDataCompletedDelegate, userState);
        }
    }
}
