//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex.PMH.Tester.pmh {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmh.plexxis.com", ConfigurationName="pmh.APISoap")]
    public interface APISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionConnect", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void ConnectionRelease(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionRelease", ReplyAction="*")]
        System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int ConnectionStatus(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.QueryResult QryExecute(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecute", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QryExecuteAsync(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecuteXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode QryExecuteXml(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecuteXml", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> QryExecuteXmlAsync(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/IUD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.MethodResult IUD(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/IUD", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> IUDAsync(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.QueryResult[] DeviceSynchronization(int ConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronization", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult[]> DeviceSynchronizationAsync(int ConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void Sync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/Sync", ReplyAction="*")]
        System.Threading.Tasks.Task SyncAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.QueryResult QueryDatabase(int ConnectionId, string Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QueryDatabaseAsync(int ConnectionId, string Query);
        
        // CODEGEN: Parameter 'userDataId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.DeviceSynchronizeResponse DeviceSynchronize(Plex.PMH.Tester.pmh.DeviceSynchronizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronize", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizeResponse> DeviceSynchronizeAsync(Plex.PMH.Tester.pmh.DeviceSynchronizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceRequestId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.MethodResult DeviceRequestId(int connectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceRequestId", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> DeviceRequestIdAsync(int connectionId);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeviceSynchronizeMethodResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QueryResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class MethodResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private int responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class IUDData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private string[] columnNamesField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] ColumnNames {
            get {
                return this.columnNamesField;
            }
            set {
                this.columnNamesField = value;
                this.RaisePropertyChanged("ColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dBActionField;
        
        private int rowVersionField;
        
        private object[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DBAction {
            get {
                return this.dBActionField;
            }
            set {
                this.dBActionField = value;
                this.RaisePropertyChanged("DBAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int RowVersion {
            get {
                return this.rowVersionField;
            }
            set {
                this.rowVersionField = value;
                this.RaisePropertyChanged("RowVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public object[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Column : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private System.Nullable<int> columnSequenceField;
        
        private string dataTypeField;
        
        private System.Nullable<int> dataLengthField;
        
        private System.Nullable<int> dataPrecisionField;
        
        private System.Nullable<int> dataScaleField;
        
        private System.Nullable<bool> allowDbNullField;
        
        private System.Nullable<bool> isReadOnlyField;
        
        private System.Nullable<bool> isLongField;
        
        private System.Nullable<bool> isKeyField;
        
        private string keyTypeField;
        
        private System.Nullable<bool> isUniqueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ColumnSequence {
            get {
                return this.columnSequenceField;
            }
            set {
                this.columnSequenceField = value;
                this.RaisePropertyChanged("ColumnSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DataPrecision {
            get {
                return this.dataPrecisionField;
            }
            set {
                this.dataPrecisionField = value;
                this.RaisePropertyChanged("DataPrecision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DataScale {
            get {
                return this.dataScaleField;
            }
            set {
                this.dataScaleField = value;
                this.RaisePropertyChanged("DataScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> AllowDbNull {
            get {
                return this.allowDbNullField;
            }
            set {
                this.allowDbNullField = value;
                this.RaisePropertyChanged("AllowDbNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
                this.RaisePropertyChanged("IsLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsKey {
            get {
                return this.isKeyField;
            }
            set {
                this.isKeyField = value;
                this.RaisePropertyChanged("IsKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> IsUnique {
            get {
                return this.isUniqueField;
            }
            set {
                this.isUniqueField = value;
                this.RaisePropertyChanged("IsUnique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class DeviceSynchronizeMethodResult : MethodResult {
        
        private System.DateTime startTimeStampField;
        
        private System.DateTime completionTimeStampField;
        
        private QueryResult[] resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartTimeStamp {
            get {
                return this.startTimeStampField;
            }
            set {
                this.startTimeStampField = value;
                this.RaisePropertyChanged("StartTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CompletionTimeStamp {
            get {
                return this.completionTimeStampField;
            }
            set {
                this.completionTimeStampField = value;
                this.RaisePropertyChanged("CompletionTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public QueryResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class QueryResult : MethodResult {
        
        private System.DateTime startTimeStampField;
        
        private System.DateTime completionTimeStampField;
        
        private int dBErrorCodeField;
        
        private string dBErrorMessageField;
        
        private Column[] columnsField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime StartTimeStamp {
            get {
                return this.startTimeStampField;
            }
            set {
                this.startTimeStampField = value;
                this.RaisePropertyChanged("StartTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CompletionTimeStamp {
            get {
                return this.completionTimeStampField;
            }
            set {
                this.completionTimeStampField = value;
                this.RaisePropertyChanged("CompletionTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DBErrorCode {
            get {
                return this.dBErrorCodeField;
            }
            set {
                this.dBErrorCodeField = value;
                this.RaisePropertyChanged("DBErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DBErrorMessage {
            get {
                return this.dBErrorMessageField;
            }
            set {
                this.dBErrorMessageField = value;
                this.RaisePropertyChanged("DBErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Column[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeviceSynchronize", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class DeviceSynchronizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        public int connectionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=1)]
        public int deviceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> userDataId;
        
        public DeviceSynchronizeRequest() {
        }
        
        public DeviceSynchronizeRequest(int connectionId, int deviceId, System.Nullable<int> userDataId) {
            this.connectionId = connectionId;
            this.deviceId = deviceId;
            this.userDataId = userDataId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeviceSynchronizeResponse", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class DeviceSynchronizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        public Plex.PMH.Tester.pmh.DeviceSynchronizeMethodResult DeviceSynchronizeResult;
        
        public DeviceSynchronizeResponse() {
        }
        
        public DeviceSynchronizeResponse(Plex.PMH.Tester.pmh.DeviceSynchronizeMethodResult DeviceSynchronizeResult) {
            this.DeviceSynchronizeResult = DeviceSynchronizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : Plex.PMH.Tester.pmh.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<Plex.PMH.Tester.pmh.APISoap>, Plex.PMH.Tester.pmh.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Plex.PMH.Tester.pmh.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnect(ClientId, AppId, Database, User, Password);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnectAsync(ClientId, AppId, Database, User, Password);
        }
        
        public void ConnectionRelease(int nConnectionId) {
            base.Channel.ConnectionRelease(nConnectionId);
        }
        
        public System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId) {
            return base.Channel.ConnectionReleaseAsync(nConnectionId);
        }
        
        public int ConnectionStatus(int nConnectionId) {
            return base.Channel.ConnectionStatus(nConnectionId);
        }
        
        public System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId) {
            return base.Channel.ConnectionStatusAsync(nConnectionId);
        }
        
        public Plex.PMH.Tester.pmh.QueryResult QryExecute(int nConnectionId, string QueryName) {
            return base.Channel.QryExecute(nConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QryExecuteAsync(int nConnectionId, string QueryName) {
            return base.Channel.QryExecuteAsync(nConnectionId, QueryName);
        }
        
        public System.Xml.XmlNode QryExecuteXml(int nConnectionId, string QueryName) {
            return base.Channel.QryExecuteXml(nConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> QryExecuteXmlAsync(int nConnectionId, string QueryName) {
            return base.Channel.QryExecuteXmlAsync(nConnectionId, QueryName);
        }
        
        public Plex.PMH.Tester.pmh.MethodResult IUD(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData) {
            return base.Channel.IUD(nConnectionId, DBModData);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> IUDAsync(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData) {
            return base.Channel.IUDAsync(nConnectionId, DBModData);
        }
        
        public Plex.PMH.Tester.pmh.QueryResult[] DeviceSynchronization(int ConnectionId) {
            return base.Channel.DeviceSynchronization(ConnectionId);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult[]> DeviceSynchronizationAsync(int ConnectionId) {
            return base.Channel.DeviceSynchronizationAsync(ConnectionId);
        }
        
        public void Sync() {
            base.Channel.Sync();
        }
        
        public System.Threading.Tasks.Task SyncAsync() {
            return base.Channel.SyncAsync();
        }
        
        public Plex.PMH.Tester.pmh.QueryResult QueryDatabase(int ConnectionId, string Query) {
            return base.Channel.QueryDatabase(ConnectionId, Query);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QueryDatabaseAsync(int ConnectionId, string Query) {
            return base.Channel.QueryDatabaseAsync(ConnectionId, Query);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plex.PMH.Tester.pmh.DeviceSynchronizeResponse Plex.PMH.Tester.pmh.APISoap.DeviceSynchronize(Plex.PMH.Tester.pmh.DeviceSynchronizeRequest request) {
            return base.Channel.DeviceSynchronize(request);
        }
        
        public Plex.PMH.Tester.pmh.DeviceSynchronizeMethodResult DeviceSynchronize(int connectionId, int deviceId, System.Nullable<int> userDataId) {
            Plex.PMH.Tester.pmh.DeviceSynchronizeRequest inValue = new Plex.PMH.Tester.pmh.DeviceSynchronizeRequest();
            inValue.connectionId = connectionId;
            inValue.deviceId = deviceId;
            inValue.userDataId = userDataId;
            Plex.PMH.Tester.pmh.DeviceSynchronizeResponse retVal = ((Plex.PMH.Tester.pmh.APISoap)(this)).DeviceSynchronize(inValue);
            return retVal.DeviceSynchronizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizeResponse> Plex.PMH.Tester.pmh.APISoap.DeviceSynchronizeAsync(Plex.PMH.Tester.pmh.DeviceSynchronizeRequest request) {
            return base.Channel.DeviceSynchronizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizeResponse> DeviceSynchronizeAsync(int connectionId, int deviceId, System.Nullable<int> userDataId) {
            Plex.PMH.Tester.pmh.DeviceSynchronizeRequest inValue = new Plex.PMH.Tester.pmh.DeviceSynchronizeRequest();
            inValue.connectionId = connectionId;
            inValue.deviceId = deviceId;
            inValue.userDataId = userDataId;
            return ((Plex.PMH.Tester.pmh.APISoap)(this)).DeviceSynchronizeAsync(inValue);
        }
        
        public Plex.PMH.Tester.pmh.MethodResult DeviceRequestId(int connectionId) {
            return base.Channel.DeviceRequestId(connectionId);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> DeviceRequestIdAsync(int connectionId) {
            return base.Channel.DeviceRequestIdAsync(connectionId);
        }
    }
}
