//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex.PMH.Tester.pmh {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmh.plexxis.com", ConfigurationName="pmh.APISoap")]
    public interface APISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionConnect", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void ConnectionRelease(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionRelease", ReplyAction="*")]
        System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        int ConnectionStatus(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ConnectionStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool QryCreate(int nAppId, string sAppAuthKey, Plex.PMH.Tester.pmh.QueryDefinition Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> QryCreateAsync(int nAppId, string sAppAuthKey, Plex.PMH.Tester.pmh.QueryDefinition Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName);
        
        // CODEGEN: Parameter 'Time' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.QryExecuteResponse QryExecute(Plex.PMH.Tester.pmh.QryExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QryExecute", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QryExecuteResponse> QryExecuteAsync(Plex.PMH.Tester.pmh.QryExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryExecuteXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        System.Xml.XmlNode QueryExecuteXml(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryExecuteXml", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> QueryExecuteXmlAsync(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryExecuteObj", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.QueryResult QueryExecuteObj(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/QueryExecuteObj", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QueryExecuteObjAsync(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/IUD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.MethodResult IUD(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/IUD", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> IUDAsync(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData);
        
        // CODEGEN: Parameter 'DeviceSynchronizationResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronization", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        Plex.PMH.Tester.pmh.DeviceSynchronizationResponse DeviceSynchronization(Plex.PMH.Tester.pmh.DeviceSynchronizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/DeviceSynchronization", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizationResponse> DeviceSynchronizationAsync(Plex.PMH.Tester.pmh.DeviceSynchronizationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        void Sync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/Sync", ReplyAction="*")]
        System.Threading.Tasks.Task SyncAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class MethodResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private int responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class IUDData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private string[] columnNamesField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] ColumnNames {
            get {
                return this.columnNamesField;
            }
            set {
                this.columnNamesField = value;
                this.RaisePropertyChanged("ColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RowAction actionField;
        
        private object[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RowAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public object[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public enum RowAction {
        
        /// <remarks/>
        Read,
        
        /// <remarks/>
        Create,
        
        /// <remarks/>
        Modify,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Column : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private System.Nullable<int> columnSequenceField;
        
        private string dataTypeField;
        
        private System.Nullable<int> dataLengthField;
        
        private System.Nullable<int> dataPrecisionField;
        
        private System.Nullable<int> dataScaleField;
        
        private System.Nullable<bool> allowDbNullField;
        
        private System.Nullable<bool> isReadOnlyField;
        
        private System.Nullable<bool> isLongField;
        
        private System.Nullable<bool> isKeyField;
        
        private string keyTypeField;
        
        private System.Nullable<bool> isUniqueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ColumnSequence {
            get {
                return this.columnSequenceField;
            }
            set {
                this.columnSequenceField = value;
                this.RaisePropertyChanged("ColumnSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DataPrecision {
            get {
                return this.dataPrecisionField;
            }
            set {
                this.dataPrecisionField = value;
                this.RaisePropertyChanged("DataPrecision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DataScale {
            get {
                return this.dataScaleField;
            }
            set {
                this.dataScaleField = value;
                this.RaisePropertyChanged("DataScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> AllowDbNull {
            get {
                return this.allowDbNullField;
            }
            set {
                this.allowDbNullField = value;
                this.RaisePropertyChanged("AllowDbNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
                this.RaisePropertyChanged("IsLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsKey {
            get {
                return this.isKeyField;
            }
            set {
                this.isKeyField = value;
                this.RaisePropertyChanged("IsKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> IsUnique {
            get {
                return this.isUniqueField;
            }
            set {
                this.isUniqueField = value;
                this.RaisePropertyChanged("IsUnique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class QueryResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Column[] columnsField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Column[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Condition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private string columnNVLField;
        
        private string columnValueField;
        
        private string operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ColumnNVL {
            get {
                return this.columnNVLField;
            }
            set {
                this.columnNVLField = value;
                this.RaisePropertyChanged("ColumnNVL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ColumnValue {
            get {
                return this.columnValueField;
            }
            set {
                this.columnValueField = value;
                this.RaisePropertyChanged("ColumnValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class QueryDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryNameField;
        
        private string tableNameField;
        
        private bool trackDeltaField;
        
        private string[] columnNamesField;
        
        private Condition[] whereClausesField;
        
        private string sqlField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QueryName {
            get {
                return this.queryNameField;
            }
            set {
                this.queryNameField = value;
                this.RaisePropertyChanged("QueryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool TrackDelta {
            get {
                return this.trackDeltaField;
            }
            set {
                this.trackDeltaField = value;
                this.RaisePropertyChanged("TrackDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] ColumnNames {
            get {
                return this.columnNamesField;
            }
            set {
                this.columnNamesField = value;
                this.RaisePropertyChanged("ColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Condition[] WhereClauses {
            get {
                return this.whereClausesField;
            }
            set {
                this.whereClausesField = value;
                this.RaisePropertyChanged("WhereClauses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
                this.RaisePropertyChanged("Sql");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QryExecute", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class QryExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        public int nConnectionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=1)]
        public string QueryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Time;
        
        public QryExecuteRequest() {
        }
        
        public QryExecuteRequest(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            this.nConnectionId = nConnectionId;
            this.QueryName = QueryName;
            this.Time = Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QryExecuteResponse", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class QryExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        public System.Xml.XmlNode QryExecuteResult;
        
        public QryExecuteResponse() {
        }
        
        public QryExecuteResponse(System.Xml.XmlNode QryExecuteResult) {
            this.QryExecuteResult = QryExecuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeviceSynchronization", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class DeviceSynchronizationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        public int ConnectionId;
        
        public DeviceSynchronizationRequest() {
        }
        
        public DeviceSynchronizationRequest(int ConnectionId) {
            this.ConnectionId = ConnectionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeviceSynchronizationResponse", WrapperNamespace="http://pmh.plexxis.com", IsWrapped=true)]
    public partial class DeviceSynchronizationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("XmlDocument")]
        public System.Xml.XmlNode[] DeviceSynchronizationResult;
        
        public DeviceSynchronizationResponse() {
        }
        
        public DeviceSynchronizationResponse(System.Xml.XmlNode[] DeviceSynchronizationResult) {
            this.DeviceSynchronizationResult = DeviceSynchronizationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : Plex.PMH.Tester.pmh.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<Plex.PMH.Tester.pmh.APISoap>, Plex.PMH.Tester.pmh.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Plex.PMH.Tester.pmh.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnect(ClientId, AppId, Database, User, Password);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnectAsync(ClientId, AppId, Database, User, Password);
        }
        
        public void ConnectionRelease(int nConnectionId) {
            base.Channel.ConnectionRelease(nConnectionId);
        }
        
        public System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId) {
            return base.Channel.ConnectionReleaseAsync(nConnectionId);
        }
        
        public int ConnectionStatus(int nConnectionId) {
            return base.Channel.ConnectionStatus(nConnectionId);
        }
        
        public System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId) {
            return base.Channel.ConnectionStatusAsync(nConnectionId);
        }
        
        public bool QryCreate(int nAppId, string sAppAuthKey, Plex.PMH.Tester.pmh.QueryDefinition Query) {
            return base.Channel.QryCreate(nAppId, sAppAuthKey, Query);
        }
        
        public System.Threading.Tasks.Task<bool> QryCreateAsync(int nAppId, string sAppAuthKey, Plex.PMH.Tester.pmh.QueryDefinition Query) {
            return base.Channel.QryCreateAsync(nAppId, sAppAuthKey, Query);
        }
        
        public bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName) {
            return base.Channel.QryDelete(nAppId, sAppAuthKey, sQueryName);
        }
        
        public System.Threading.Tasks.Task<bool> QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName) {
            return base.Channel.QryDeleteAsync(nAppId, sAppAuthKey, sQueryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plex.PMH.Tester.pmh.QryExecuteResponse Plex.PMH.Tester.pmh.APISoap.QryExecute(Plex.PMH.Tester.pmh.QryExecuteRequest request) {
            return base.Channel.QryExecute(request);
        }
        
        public System.Xml.XmlNode QryExecute(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            Plex.PMH.Tester.pmh.QryExecuteRequest inValue = new Plex.PMH.Tester.pmh.QryExecuteRequest();
            inValue.nConnectionId = nConnectionId;
            inValue.QueryName = QueryName;
            inValue.Time = Time;
            Plex.PMH.Tester.pmh.QryExecuteResponse retVal = ((Plex.PMH.Tester.pmh.APISoap)(this)).QryExecute(inValue);
            return retVal.QryExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QryExecuteResponse> Plex.PMH.Tester.pmh.APISoap.QryExecuteAsync(Plex.PMH.Tester.pmh.QryExecuteRequest request) {
            return base.Channel.QryExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QryExecuteResponse> QryExecuteAsync(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            Plex.PMH.Tester.pmh.QryExecuteRequest inValue = new Plex.PMH.Tester.pmh.QryExecuteRequest();
            inValue.nConnectionId = nConnectionId;
            inValue.QueryName = QueryName;
            inValue.Time = Time;
            return ((Plex.PMH.Tester.pmh.APISoap)(this)).QryExecuteAsync(inValue);
        }
        
        public System.Xml.XmlNode QueryExecuteXml(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteXml(nConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> QueryExecuteXmlAsync(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteXmlAsync(nConnectionId, QueryName);
        }
        
        public Plex.PMH.Tester.pmh.QueryResult QueryExecuteObj(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteObj(nConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.QueryResult> QueryExecuteObjAsync(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteObjAsync(nConnectionId, QueryName);
        }
        
        public Plex.PMH.Tester.pmh.MethodResult IUD(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData) {
            return base.Channel.IUD(nConnectionId, DBModData);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.MethodResult> IUDAsync(int nConnectionId, Plex.PMH.Tester.pmh.IUDData DBModData) {
            return base.Channel.IUDAsync(nConnectionId, DBModData);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plex.PMH.Tester.pmh.DeviceSynchronizationResponse Plex.PMH.Tester.pmh.APISoap.DeviceSynchronization(Plex.PMH.Tester.pmh.DeviceSynchronizationRequest request) {
            return base.Channel.DeviceSynchronization(request);
        }
        
        public System.Xml.XmlNode[] DeviceSynchronization(int ConnectionId) {
            Plex.PMH.Tester.pmh.DeviceSynchronizationRequest inValue = new Plex.PMH.Tester.pmh.DeviceSynchronizationRequest();
            inValue.ConnectionId = ConnectionId;
            Plex.PMH.Tester.pmh.DeviceSynchronizationResponse retVal = ((Plex.PMH.Tester.pmh.APISoap)(this)).DeviceSynchronization(inValue);
            return retVal.DeviceSynchronizationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizationResponse> Plex.PMH.Tester.pmh.APISoap.DeviceSynchronizationAsync(Plex.PMH.Tester.pmh.DeviceSynchronizationRequest request) {
            return base.Channel.DeviceSynchronizationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.pmh.DeviceSynchronizationResponse> DeviceSynchronizationAsync(int ConnectionId) {
            Plex.PMH.Tester.pmh.DeviceSynchronizationRequest inValue = new Plex.PMH.Tester.pmh.DeviceSynchronizationRequest();
            inValue.ConnectionId = ConnectionId;
            return ((Plex.PMH.Tester.pmh.APISoap)(this)).DeviceSynchronizationAsync(inValue);
        }
        
        public void Sync() {
            base.Channel.Sync();
        }
        
        public System.Threading.Tasks.Task SyncAsync() {
            return base.Channel.SyncAsync();
        }
    }
}
