//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plex.PMH.Tester.PMH {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmh.plexxis.com/api", ConfigurationName="PMH.APISoap")]
    public interface APISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppGetTableDefinition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.TableDefinition[] AppGetTableDefinition(int nAppId, string sAppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppGetTableDefinition", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.TableDefinition[]> AppGetTableDefinitionAsync(int nAppId, string sAppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppGetQueries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.QueryDefinition[] AppGetQueries(int AppId, string AppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppGetQueries", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.QueryDefinition[]> AppGetQueriesAsync(int AppId, string AppAuthKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ClientGetDatabaseList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        void ClientGetDatabaseList(int nClientId, int nAppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ClientGetDatabaseList", ReplyAction="*")]
        System.Threading.Tasks.Task ClientGetDatabaseListAsync(int nClientId, int nAppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionConnect", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionRelease", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        void ConnectionRelease(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionRelease", ReplyAction="*")]
        System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        int ConnectionStatus(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/ConnectionStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryCreate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        bool QryCreate(int nAppId, string sAppAuthKey, Plex.PMH.Tester.PMH.QueryDefinition Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryCreate", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> QryCreateAsync(int nAppId, string sAppAuthKey, Plex.PMH.Tester.PMH.QueryDefinition Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryDelete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryDelete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName);
        
        // CODEGEN: Parameter 'Time' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryExecute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.QryExecuteResponse QryExecute(Plex.PMH.Tester.PMH.QryExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryExecute", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.QryExecuteResponse> QryExecuteAsync(Plex.PMH.Tester.PMH.QryExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QueryExecuteXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        string QueryExecuteXml(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QueryExecuteXml", ReplyAction="*")]
        System.Threading.Tasks.Task<string> QueryExecuteXmlAsync(int nConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetAppQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.AppQueries GetAppQuery(int ConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetAppQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.AppQueries> GetAppQueryAsync(int ConnectionId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/IUD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        System.Xml.XmlNode IUD(int nConnectionId, Plex.PMH.Tester.PMH.IUDData DBModData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/IUD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> IUDAsync(int nConnectionId, Plex.PMH.Tester.PMH.IUDData DBModData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QueryDatabase", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        System.Xml.XmlNode QueryDatabase(int nConnectionId, string Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QueryDatabase", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> QueryDatabaseAsync(int nConnectionId, string Query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryCreateOffTable", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        bool QryCreateOffTable(int AppId, string Auth, int TableId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/QryCreateOffTable", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> QryCreateOffTableAsync(int AppId, string Auth, int TableId, string QueryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/Sync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        void Sync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/Sync", ReplyAction="*")]
        System.Threading.Tasks.Task SyncAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetCommandRepo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.Command[] GetCommandRepo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetCommandRepo", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Command[]> GetCommandRepoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetConnectionRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.ConnectionData[] GetConnectionRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetConnectionRepository", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.ConnectionData[]> GetConnectionRepositoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetConsumerRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.Consumer[] GetConsumerRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetConsumerRepository", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Consumer[]> GetConsumerRepositoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetLogRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.Log[] GetLogRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetLogRepository", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Log[]> GetLogRepositoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetResponseRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.Response[] GetResponseRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetResponseRepository", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Response[]> GetResponseRepositoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/LogsGetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        Plex.PMH.Tester.PMH.Log[] LogsGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/LogsGetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Log[]> LogsGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppTableColumns", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        int AppTableColumns(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/AppTableColumns", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AppTableColumnsAsync(int TableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        int GetCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/Log", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        void Log(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/Log", ReplyAction="*")]
        System.Threading.Tasks.Task LogAsync(string s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/IssueCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        void IssueCommand(int ClientId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/IssueCommand", ReplyAction="*")]
        System.Threading.Tasks.Task IssueCommandAsync(int ClientId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Row[]))]
        string GetResponse(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/api/GetResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetResponseAsync(int i);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class TableDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private bool allowInsertField;
        
        private bool allowDeleteField;
        
        private bool allowUpdateField;
        
        private bool allowQueryField;
        
        private Column[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool AllowInsert {
            get {
                return this.allowInsertField;
            }
            set {
                this.allowInsertField = value;
                this.RaisePropertyChanged("AllowInsert");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool AllowDelete {
            get {
                return this.allowDeleteField;
            }
            set {
                this.allowDeleteField = value;
                this.RaisePropertyChanged("AllowDelete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool AllowUpdate {
            get {
                return this.allowUpdateField;
            }
            set {
                this.allowUpdateField = value;
                this.RaisePropertyChanged("AllowUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool AllowQuery {
            get {
                return this.allowQueryField;
            }
            set {
                this.allowQueryField = value;
                this.RaisePropertyChanged("AllowQuery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public Column[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Column : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private System.Nullable<int> columnSequenceField;
        
        private string dataTypeField;
        
        private System.Nullable<int> dataLengthField;
        
        private System.Nullable<int> dataPrecisionField;
        
        private System.Nullable<int> dataScaleField;
        
        private System.Nullable<bool> allowDbNullField;
        
        private System.Nullable<bool> isReadOnlyField;
        
        private System.Nullable<bool> isLongField;
        
        private System.Nullable<bool> isKeyField;
        
        private string keyTypeField;
        
        private System.Nullable<bool> isUniqueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ColumnSequence {
            get {
                return this.columnSequenceField;
            }
            set {
                this.columnSequenceField = value;
                this.RaisePropertyChanged("ColumnSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DataPrecision {
            get {
                return this.dataPrecisionField;
            }
            set {
                this.dataPrecisionField = value;
                this.RaisePropertyChanged("DataPrecision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DataScale {
            get {
                return this.dataScaleField;
            }
            set {
                this.dataScaleField = value;
                this.RaisePropertyChanged("DataScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> AllowDbNull {
            get {
                return this.allowDbNullField;
            }
            set {
                this.allowDbNullField = value;
                this.RaisePropertyChanged("AllowDbNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
                this.RaisePropertyChanged("IsLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsKey {
            get {
                return this.isKeyField;
            }
            set {
                this.isKeyField = value;
                this.RaisePropertyChanged("IsKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> IsUnique {
            get {
                return this.isUniqueField;
            }
            set {
                this.isUniqueField = value;
                this.RaisePropertyChanged("IsUnique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string respField;
        
        private bool isErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Resp {
            get {
                return this.respField;
            }
            set {
                this.respField = value;
                this.RaisePropertyChanged("Resp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
                this.RaisePropertyChanged("IsError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LogPriority priorityField;
        
        private System.DateTime dateField;
        
        private string recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LogPriority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public enum LogPriority {
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        BelowAverage,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        AboveAverage,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Consumer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int consumerIdField;
        
        private int clientIdField;
        
        private int databaseIdField;
        
        private int appIdField;
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ConsumerId {
            get {
                return this.consumerIdField;
            }
            set {
                this.consumerIdField = value;
                this.RaisePropertyChanged("ConsumerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DatabaseId {
            get {
                return this.databaseIdField;
            }
            set {
                this.databaseIdField = value;
                this.RaisePropertyChanged("DatabaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
                this.RaisePropertyChanged("AppId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Stopwatch : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class ConnectionData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int clientIdField;
        
        private string keyField;
        
        private System.DateTime initTimeField;
        
        private Stopwatch lastCheckField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime InitTime {
            get {
                return this.initTimeField;
            }
            set {
                this.initTimeField = value;
                this.RaisePropertyChanged("InitTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Stopwatch LastCheck {
            get {
                return this.lastCheckField;
            }
            set {
                this.lastCheckField = value;
                this.RaisePropertyChanged("LastCheck");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Command : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int clientIdField;
        
        private int requestIdField;
        
        private object[] paramsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public object[] Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("Params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Row : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RowAction actionField;
        
        private object[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RowAction Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public object[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public enum RowAction {
        
        /// <remarks/>
        Read,
        
        /// <remarks/>
        Create,
        
        /// <remarks/>
        Modify,
        
        /// <remarks/>
        Delete,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class IUDData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tableNameField;
        
        private string[] columnNameField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AppQueries))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public abstract partial class PlexxisDataTransferObjects : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class AppQueries : PlexxisDataTransferObjects {
        
        private int queryIdField;
        
        private int appIdField;
        
        private string nameField;
        
        private string descriptionField;
        
        private int tableIdField;
        
        private bool isDeltaField;
        
        private string sqlField;
        
        private int seqLimitTimeSpanField;
        
        private int seqLimitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int QueryId {
            get {
                return this.queryIdField;
            }
            set {
                this.queryIdField = value;
                this.RaisePropertyChanged("QueryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
                this.RaisePropertyChanged("AppId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int TableId {
            get {
                return this.tableIdField;
            }
            set {
                this.tableIdField = value;
                this.RaisePropertyChanged("TableId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsDelta {
            get {
                return this.isDeltaField;
            }
            set {
                this.isDeltaField = value;
                this.RaisePropertyChanged("IsDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
                this.RaisePropertyChanged("Sql");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int SeqLimitTimeSpan {
            get {
                return this.seqLimitTimeSpanField;
            }
            set {
                this.seqLimitTimeSpanField = value;
                this.RaisePropertyChanged("SeqLimitTimeSpan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int SeqLimit {
            get {
                return this.seqLimitField;
            }
            set {
                this.seqLimitField = value;
                this.RaisePropertyChanged("SeqLimit");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class MethodResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgField;
        
        private int responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("Msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class Condition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private string columnNVLField;
        
        private string columnValueField;
        
        private string operatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ColumnNVL {
            get {
                return this.columnNVLField;
            }
            set {
                this.columnNVLField = value;
                this.RaisePropertyChanged("ColumnNVL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ColumnValue {
            get {
                return this.columnValueField;
            }
            set {
                this.columnValueField = value;
                this.RaisePropertyChanged("ColumnValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("Operator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com/api")]
    public partial class QueryDefinition : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string queryNameField;
        
        private string tableNameField;
        
        private bool trackDeltaField;
        
        private string[] columnNamesField;
        
        private Condition[] whereClausesField;
        
        private string sqlField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string QueryName {
            get {
                return this.queryNameField;
            }
            set {
                this.queryNameField = value;
                this.RaisePropertyChanged("QueryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
                this.RaisePropertyChanged("TableName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool TrackDelta {
            get {
                return this.trackDeltaField;
            }
            set {
                this.trackDeltaField = value;
                this.RaisePropertyChanged("TrackDelta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] ColumnNames {
            get {
                return this.columnNamesField;
            }
            set {
                this.columnNamesField = value;
                this.RaisePropertyChanged("ColumnNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Condition[] WhereClauses {
            get {
                return this.whereClausesField;
            }
            set {
                this.whereClausesField = value;
                this.RaisePropertyChanged("WhereClauses");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
                this.RaisePropertyChanged("Sql");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QryExecute", WrapperNamespace="http://pmh.plexxis.com/api", IsWrapped=true)]
    public partial class QryExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com/api", Order=0)]
        public int nConnectionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com/api", Order=1)]
        public string QueryName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com/api", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> Time;
        
        public QryExecuteRequest() {
        }
        
        public QryExecuteRequest(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            this.nConnectionId = nConnectionId;
            this.QueryName = QueryName;
            this.Time = Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QryExecuteResponse", WrapperNamespace="http://pmh.plexxis.com/api", IsWrapped=true)]
    public partial class QryExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pmh.plexxis.com/api", Order=0)]
        public System.Xml.XmlNode QryExecuteResult;
        
        public QryExecuteResponse() {
        }
        
        public QryExecuteResponse(System.Xml.XmlNode QryExecuteResult) {
            this.QryExecuteResult = QryExecuteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : Plex.PMH.Tester.PMH.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<Plex.PMH.Tester.PMH.APISoap>, Plex.PMH.Tester.PMH.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Plex.PMH.Tester.PMH.TableDefinition[] AppGetTableDefinition(int nAppId, string sAppAuthKey) {
            return base.Channel.AppGetTableDefinition(nAppId, sAppAuthKey);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.TableDefinition[]> AppGetTableDefinitionAsync(int nAppId, string sAppAuthKey) {
            return base.Channel.AppGetTableDefinitionAsync(nAppId, sAppAuthKey);
        }
        
        public Plex.PMH.Tester.PMH.QueryDefinition[] AppGetQueries(int AppId, string AppAuthKey) {
            return base.Channel.AppGetQueries(AppId, AppAuthKey);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.QueryDefinition[]> AppGetQueriesAsync(int AppId, string AppAuthKey) {
            return base.Channel.AppGetQueriesAsync(AppId, AppAuthKey);
        }
        
        public void ClientGetDatabaseList(int nClientId, int nAppId) {
            base.Channel.ClientGetDatabaseList(nClientId, nAppId);
        }
        
        public System.Threading.Tasks.Task ClientGetDatabaseListAsync(int nClientId, int nAppId) {
            return base.Channel.ClientGetDatabaseListAsync(nClientId, nAppId);
        }
        
        public Plex.PMH.Tester.PMH.MethodResult ConnectionConnect(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnect(ClientId, AppId, Database, User, Password);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.MethodResult> ConnectionConnectAsync(int ClientId, int AppId, string Database, string User, string Password) {
            return base.Channel.ConnectionConnectAsync(ClientId, AppId, Database, User, Password);
        }
        
        public void ConnectionRelease(int nConnectionId) {
            base.Channel.ConnectionRelease(nConnectionId);
        }
        
        public System.Threading.Tasks.Task ConnectionReleaseAsync(int nConnectionId) {
            return base.Channel.ConnectionReleaseAsync(nConnectionId);
        }
        
        public int ConnectionStatus(int nConnectionId) {
            return base.Channel.ConnectionStatus(nConnectionId);
        }
        
        public System.Threading.Tasks.Task<int> ConnectionStatusAsync(int nConnectionId) {
            return base.Channel.ConnectionStatusAsync(nConnectionId);
        }
        
        public bool QryCreate(int nAppId, string sAppAuthKey, Plex.PMH.Tester.PMH.QueryDefinition Query) {
            return base.Channel.QryCreate(nAppId, sAppAuthKey, Query);
        }
        
        public System.Threading.Tasks.Task<bool> QryCreateAsync(int nAppId, string sAppAuthKey, Plex.PMH.Tester.PMH.QueryDefinition Query) {
            return base.Channel.QryCreateAsync(nAppId, sAppAuthKey, Query);
        }
        
        public bool QryDelete(int nAppId, string sAppAuthKey, string sQueryName) {
            return base.Channel.QryDelete(nAppId, sAppAuthKey, sQueryName);
        }
        
        public System.Threading.Tasks.Task<bool> QryDeleteAsync(int nAppId, string sAppAuthKey, string sQueryName) {
            return base.Channel.QryDeleteAsync(nAppId, sAppAuthKey, sQueryName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plex.PMH.Tester.PMH.QryExecuteResponse Plex.PMH.Tester.PMH.APISoap.QryExecute(Plex.PMH.Tester.PMH.QryExecuteRequest request) {
            return base.Channel.QryExecute(request);
        }
        
        public System.Xml.XmlNode QryExecute(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            Plex.PMH.Tester.PMH.QryExecuteRequest inValue = new Plex.PMH.Tester.PMH.QryExecuteRequest();
            inValue.nConnectionId = nConnectionId;
            inValue.QueryName = QueryName;
            inValue.Time = Time;
            Plex.PMH.Tester.PMH.QryExecuteResponse retVal = ((Plex.PMH.Tester.PMH.APISoap)(this)).QryExecute(inValue);
            return retVal.QryExecuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.QryExecuteResponse> Plex.PMH.Tester.PMH.APISoap.QryExecuteAsync(Plex.PMH.Tester.PMH.QryExecuteRequest request) {
            return base.Channel.QryExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.QryExecuteResponse> QryExecuteAsync(int nConnectionId, string QueryName, System.Nullable<System.DateTime> Time) {
            Plex.PMH.Tester.PMH.QryExecuteRequest inValue = new Plex.PMH.Tester.PMH.QryExecuteRequest();
            inValue.nConnectionId = nConnectionId;
            inValue.QueryName = QueryName;
            inValue.Time = Time;
            return ((Plex.PMH.Tester.PMH.APISoap)(this)).QryExecuteAsync(inValue);
        }
        
        public string QueryExecuteXml(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteXml(nConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<string> QueryExecuteXmlAsync(int nConnectionId, string QueryName) {
            return base.Channel.QueryExecuteXmlAsync(nConnectionId, QueryName);
        }
        
        public Plex.PMH.Tester.PMH.AppQueries GetAppQuery(int ConnectionId, string QueryName) {
            return base.Channel.GetAppQuery(ConnectionId, QueryName);
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.AppQueries> GetAppQueryAsync(int ConnectionId, string QueryName) {
            return base.Channel.GetAppQueryAsync(ConnectionId, QueryName);
        }
        
        public System.Xml.XmlNode IUD(int nConnectionId, Plex.PMH.Tester.PMH.IUDData DBModData) {
            return base.Channel.IUD(nConnectionId, DBModData);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> IUDAsync(int nConnectionId, Plex.PMH.Tester.PMH.IUDData DBModData) {
            return base.Channel.IUDAsync(nConnectionId, DBModData);
        }
        
        public System.Xml.XmlNode QueryDatabase(int nConnectionId, string Query) {
            return base.Channel.QueryDatabase(nConnectionId, Query);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> QueryDatabaseAsync(int nConnectionId, string Query) {
            return base.Channel.QueryDatabaseAsync(nConnectionId, Query);
        }
        
        public bool QryCreateOffTable(int AppId, string Auth, int TableId, string QueryName) {
            return base.Channel.QryCreateOffTable(AppId, Auth, TableId, QueryName);
        }
        
        public System.Threading.Tasks.Task<bool> QryCreateOffTableAsync(int AppId, string Auth, int TableId, string QueryName) {
            return base.Channel.QryCreateOffTableAsync(AppId, Auth, TableId, QueryName);
        }
        
        public void Sync() {
            base.Channel.Sync();
        }
        
        public System.Threading.Tasks.Task SyncAsync() {
            return base.Channel.SyncAsync();
        }
        
        public Plex.PMH.Tester.PMH.Command[] GetCommandRepo() {
            return base.Channel.GetCommandRepo();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Command[]> GetCommandRepoAsync() {
            return base.Channel.GetCommandRepoAsync();
        }
        
        public Plex.PMH.Tester.PMH.ConnectionData[] GetConnectionRepository() {
            return base.Channel.GetConnectionRepository();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.ConnectionData[]> GetConnectionRepositoryAsync() {
            return base.Channel.GetConnectionRepositoryAsync();
        }
        
        public Plex.PMH.Tester.PMH.Consumer[] GetConsumerRepository() {
            return base.Channel.GetConsumerRepository();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Consumer[]> GetConsumerRepositoryAsync() {
            return base.Channel.GetConsumerRepositoryAsync();
        }
        
        public Plex.PMH.Tester.PMH.Log[] GetLogRepository() {
            return base.Channel.GetLogRepository();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Log[]> GetLogRepositoryAsync() {
            return base.Channel.GetLogRepositoryAsync();
        }
        
        public Plex.PMH.Tester.PMH.Response[] GetResponseRepository() {
            return base.Channel.GetResponseRepository();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Response[]> GetResponseRepositoryAsync() {
            return base.Channel.GetResponseRepositoryAsync();
        }
        
        public Plex.PMH.Tester.PMH.Log[] LogsGetAll() {
            return base.Channel.LogsGetAll();
        }
        
        public System.Threading.Tasks.Task<Plex.PMH.Tester.PMH.Log[]> LogsGetAllAsync() {
            return base.Channel.LogsGetAllAsync();
        }
        
        public int AppTableColumns(int TableId) {
            return base.Channel.AppTableColumns(TableId);
        }
        
        public System.Threading.Tasks.Task<int> AppTableColumnsAsync(int TableId) {
            return base.Channel.AppTableColumnsAsync(TableId);
        }
        
        public int GetCount() {
            return base.Channel.GetCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync() {
            return base.Channel.GetCountAsync();
        }
        
        public void Log(string s) {
            base.Channel.Log(s);
        }
        
        public System.Threading.Tasks.Task LogAsync(string s) {
            return base.Channel.LogAsync(s);
        }
        
        public void IssueCommand(int ClientId, string name) {
            base.Channel.IssueCommand(ClientId, name);
        }
        
        public System.Threading.Tasks.Task IssueCommandAsync(int ClientId, string name) {
            return base.Channel.IssueCommandAsync(ClientId, name);
        }
        
        public string GetResponse(int i) {
            return base.Channel.GetResponse(i);
        }
        
        public System.Threading.Tasks.Task<string> GetResponseAsync(int i) {
            return base.Channel.GetResponseAsync(i);
        }
    }
}
