//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pmh.Manager.ManagementWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmh.plexxis.com", ConfigurationName="ManagementWebservice.ManagerSDKSoap")]
    public interface ManagerSDKSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetExternalIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetExternalIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetCommandRepo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Command[] GetCommandRepo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetConnectionRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Client[] GetConnectionRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetConsumerRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Consumer[] GetConsumerRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetLogRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Log[] GetLogRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/GetResponseRepository", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Response[] GetResponseRepository();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/LogsGetAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Log[] LogsGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/Query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.Result Query(string sql, object[] arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/NonQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int NonQuery(string sql, object[] arguments);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/RetrieveCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void RetrieveCommand(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ResetLogs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void ResetLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int AppAdd(string authKey, string title, string description, bool isClientCustomApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.APPS AppRetrieve(int appId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void AppRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.APP_TABLES AppTableRetrieve(int appTableId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int AppTableAdd(int appId, string name, string desc, int insert, int update, int delete, int select);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void AppTableRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableColumnRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void AppTableColumnRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableColumnAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int AppTableColumnAdd(int tabId, string nom, int seq, string type, int length, int prec, int scale, int nullable, int readOnly, int isLong, int isKey, string keyType, int unique, string desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/AppTableColumnRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.APP_TABLE_COLUMNS AppTableColumnRetrieve(int appTableColumnId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.CLIENTS ClientRetrieve(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void ClientRemove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int ClientAdd(int clientId, string desc, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientAppsAdd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        int ClientAppsAdd(int appId, int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientAppRetrieve", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        Pmh.Manager.ManagementWebservice.CLIENT_APPS ClientAppRetrieve(int clientAppId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmh.plexxis.com/ClientAppRemove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PlexxisDataTransferObjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Command[]))]
        void ClientAppRemove(int id);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Command : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int clientIdField;
        
        private int requestIdField;
        
        private object[] paramsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
                this.RaisePropertyChanged("RequestId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public object[] Params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("Params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CLIENT_APPS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CLIENTS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_TABLE_COLUMNS))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APP_TABLES))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(APPS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public abstract partial class PlexxisDataTransferObjects : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class CLIENT_APPS : PlexxisDataTransferObjects {
        
        private int cLIENT_APP_IDField;
        
        private int aPP_IDField;
        
        private int cLIENT_IDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CLIENT_APP_ID {
            get {
                return this.cLIENT_APP_IDField;
            }
            set {
                this.cLIENT_APP_IDField = value;
                this.RaisePropertyChanged("CLIENT_APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CLIENT_ID {
            get {
                return this.cLIENT_IDField;
            }
            set {
                this.cLIENT_IDField = value;
                this.RaisePropertyChanged("CLIENT_ID");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class CLIENTS : PlexxisDataTransferObjects {
        
        private int cLIENT_IDField;
        
        private string cLIENT_KEYField;
        
        private string dESCRIPTIONField;
        
        private System.Nullable<int> cLIENT_INSTANCE_IDField;
        
        private string cLIENT_IP_ADDRESSField;
        
        private System.Nullable<int> cLIENT_PORTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int CLIENT_ID {
            get {
                return this.cLIENT_IDField;
            }
            set {
                this.cLIENT_IDField = value;
                this.RaisePropertyChanged("CLIENT_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CLIENT_KEY {
            get {
                return this.cLIENT_KEYField;
            }
            set {
                this.cLIENT_KEYField = value;
                this.RaisePropertyChanged("CLIENT_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> CLIENT_INSTANCE_ID {
            get {
                return this.cLIENT_INSTANCE_IDField;
            }
            set {
                this.cLIENT_INSTANCE_IDField = value;
                this.RaisePropertyChanged("CLIENT_INSTANCE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CLIENT_IP_ADDRESS {
            get {
                return this.cLIENT_IP_ADDRESSField;
            }
            set {
                this.cLIENT_IP_ADDRESSField = value;
                this.RaisePropertyChanged("CLIENT_IP_ADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> CLIENT_PORT {
            get {
                return this.cLIENT_PORTField;
            }
            set {
                this.cLIENT_PORTField = value;
                this.RaisePropertyChanged("CLIENT_PORT");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class APP_TABLE_COLUMNS : PlexxisDataTransferObjects {
        
        private int tABLE_IDField;
        
        private int tABLE_COLUMN_IDField;
        
        private string cOLUMN_NAMEField;
        
        private int cOLUMN_SEQUENCEField;
        
        private string dATA_TYPEField;
        
        private System.Nullable<int> dATA_LENGTHField;
        
        private System.Nullable<int> dATA_PRECISIONField;
        
        private System.Nullable<int> dATA_SCALEField;
        
        private System.Nullable<int> aLLOW_DB_NULLField;
        
        private System.Nullable<int> iS_READ_ONLYField;
        
        private System.Nullable<int> iS_LONGField;
        
        private System.Nullable<int> iS_KEYField;
        
        private string kEY_TYPEField;
        
        private System.Nullable<int> iS_UNIQUEField;
        
        private string dESCRIPTIONField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TABLE_ID {
            get {
                return this.tABLE_IDField;
            }
            set {
                this.tABLE_IDField = value;
                this.RaisePropertyChanged("TABLE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TABLE_COLUMN_ID {
            get {
                return this.tABLE_COLUMN_IDField;
            }
            set {
                this.tABLE_COLUMN_IDField = value;
                this.RaisePropertyChanged("TABLE_COLUMN_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string COLUMN_NAME {
            get {
                return this.cOLUMN_NAMEField;
            }
            set {
                this.cOLUMN_NAMEField = value;
                this.RaisePropertyChanged("COLUMN_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int COLUMN_SEQUENCE {
            get {
                return this.cOLUMN_SEQUENCEField;
            }
            set {
                this.cOLUMN_SEQUENCEField = value;
                this.RaisePropertyChanged("COLUMN_SEQUENCE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DATA_TYPE {
            get {
                return this.dATA_TYPEField;
            }
            set {
                this.dATA_TYPEField = value;
                this.RaisePropertyChanged("DATA_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DATA_LENGTH {
            get {
                return this.dATA_LENGTHField;
            }
            set {
                this.dATA_LENGTHField = value;
                this.RaisePropertyChanged("DATA_LENGTH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<int> DATA_PRECISION {
            get {
                return this.dATA_PRECISIONField;
            }
            set {
                this.dATA_PRECISIONField = value;
                this.RaisePropertyChanged("DATA_PRECISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<int> DATA_SCALE {
            get {
                return this.dATA_SCALEField;
            }
            set {
                this.dATA_SCALEField = value;
                this.RaisePropertyChanged("DATA_SCALE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> ALLOW_DB_NULL {
            get {
                return this.aLLOW_DB_NULLField;
            }
            set {
                this.aLLOW_DB_NULLField = value;
                this.RaisePropertyChanged("ALLOW_DB_NULL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> IS_READ_ONLY {
            get {
                return this.iS_READ_ONLYField;
            }
            set {
                this.iS_READ_ONLYField = value;
                this.RaisePropertyChanged("IS_READ_ONLY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<int> IS_LONG {
            get {
                return this.iS_LONGField;
            }
            set {
                this.iS_LONGField = value;
                this.RaisePropertyChanged("IS_LONG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> IS_KEY {
            get {
                return this.iS_KEYField;
            }
            set {
                this.iS_KEYField = value;
                this.RaisePropertyChanged("IS_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string KEY_TYPE {
            get {
                return this.kEY_TYPEField;
            }
            set {
                this.kEY_TYPEField = value;
                this.RaisePropertyChanged("KEY_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> IS_UNIQUE {
            get {
                return this.iS_UNIQUEField;
            }
            set {
                this.iS_UNIQUEField = value;
                this.RaisePropertyChanged("IS_UNIQUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class APP_TABLES : PlexxisDataTransferObjects {
        
        private int tABLE_IDField;
        
        private int aPP_IDField;
        
        private string nAMEField;
        
        private string dESCRIPTIONField;
        
        private int iNSERT_ALLOWEDField;
        
        private int uPDATE_ALLOWEDField;
        
        private int dELETE_ALLOWEDField;
        
        private int qUERY_ALLOWEDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TABLE_ID {
            get {
                return this.tABLE_IDField;
            }
            set {
                this.tABLE_IDField = value;
                this.RaisePropertyChanged("TABLE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int INSERT_ALLOWED {
            get {
                return this.iNSERT_ALLOWEDField;
            }
            set {
                this.iNSERT_ALLOWEDField = value;
                this.RaisePropertyChanged("INSERT_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UPDATE_ALLOWED {
            get {
                return this.uPDATE_ALLOWEDField;
            }
            set {
                this.uPDATE_ALLOWEDField = value;
                this.RaisePropertyChanged("UPDATE_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int DELETE_ALLOWED {
            get {
                return this.dELETE_ALLOWEDField;
            }
            set {
                this.dELETE_ALLOWEDField = value;
                this.RaisePropertyChanged("DELETE_ALLOWED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int QUERY_ALLOWED {
            get {
                return this.qUERY_ALLOWEDField;
            }
            set {
                this.qUERY_ALLOWEDField = value;
                this.RaisePropertyChanged("QUERY_ALLOWED");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class APPS : PlexxisDataTransferObjects {
        
        private int aPP_IDField;
        
        private string aUTH_KEYField;
        
        private string tITLEField;
        
        private string dESCRIPTIONField;
        
        private int iS_CLIENT_CUSTOM_APPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int APP_ID {
            get {
                return this.aPP_IDField;
            }
            set {
                this.aPP_IDField = value;
                this.RaisePropertyChanged("APP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AUTH_KEY {
            get {
                return this.aUTH_KEYField;
            }
            set {
                this.aUTH_KEYField = value;
                this.RaisePropertyChanged("AUTH_KEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TITLE {
            get {
                return this.tITLEField;
            }
            set {
                this.tITLEField = value;
                this.RaisePropertyChanged("TITLE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DESCRIPTION {
            get {
                return this.dESCRIPTIONField;
            }
            set {
                this.dESCRIPTIONField = value;
                this.RaisePropertyChanged("DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int IS_CLIENT_CUSTOM_APP {
            get {
                return this.iS_CLIENT_CUSTOM_APPField;
            }
            set {
                this.iS_CLIENT_CUSTOM_APPField = value;
                this.RaisePropertyChanged("IS_CLIENT_CUSTOM_APP");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Tuple : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] valuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public object[] Values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("Values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Col : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string columnNameField;
        
        private System.Nullable<int> columnSequenceField;
        
        private string dataTypeField;
        
        private System.Nullable<int> dataLengthField;
        
        private System.Nullable<int> dataPrecisionField;
        
        private System.Nullable<int> dataScaleField;
        
        private System.Nullable<bool> allowDbNullField;
        
        private System.Nullable<bool> isReadOnlyField;
        
        private System.Nullable<bool> isLongField;
        
        private System.Nullable<bool> isKeyField;
        
        private string keyTypeField;
        
        private System.Nullable<bool> isUniqueField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
                this.RaisePropertyChanged("ColumnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> ColumnSequence {
            get {
                return this.columnSequenceField;
            }
            set {
                this.columnSequenceField = value;
                this.RaisePropertyChanged("ColumnSequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
                this.RaisePropertyChanged("DataType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
                this.RaisePropertyChanged("DataLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> DataPrecision {
            get {
                return this.dataPrecisionField;
            }
            set {
                this.dataPrecisionField = value;
                this.RaisePropertyChanged("DataPrecision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> DataScale {
            get {
                return this.dataScaleField;
            }
            set {
                this.dataScaleField = value;
                this.RaisePropertyChanged("DataScale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<bool> AllowDbNull {
            get {
                return this.allowDbNullField;
            }
            set {
                this.allowDbNullField = value;
                this.RaisePropertyChanged("AllowDbNull");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> IsReadOnly {
            get {
                return this.isReadOnlyField;
            }
            set {
                this.isReadOnlyField = value;
                this.RaisePropertyChanged("IsReadOnly");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsLong {
            get {
                return this.isLongField;
            }
            set {
                this.isLongField = value;
                this.RaisePropertyChanged("IsLong");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> IsKey {
            get {
                return this.isKeyField;
            }
            set {
                this.isKeyField = value;
                this.RaisePropertyChanged("IsKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string KeyType {
            get {
                return this.keyTypeField;
            }
            set {
                this.keyTypeField = value;
                this.RaisePropertyChanged("KeyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<bool> IsUnique {
            get {
                return this.isUniqueField;
            }
            set {
                this.isUniqueField = value;
                this.RaisePropertyChanged("IsUnique");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Col[] columnsField;
        
        private Tuple[] rowsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Col[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
                this.RaisePropertyChanged("Columns");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Tuple[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
                this.RaisePropertyChanged("Rows");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string respField;
        
        private bool isErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Resp {
            get {
                return this.respField;
            }
            set {
                this.respField = value;
                this.RaisePropertyChanged("Resp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
                this.RaisePropertyChanged("IsError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private LogPriority priorityField;
        
        private System.DateTime dateField;
        
        private string recordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LogPriority Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
                this.RaisePropertyChanged("Priority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Record {
            get {
                return this.recordField;
            }
            set {
                this.recordField = value;
                this.RaisePropertyChanged("Record");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public enum LogPriority {
        
        /// <remarks/>
        Low,
        
        /// <remarks/>
        BelowAverage,
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        AboveAverage,
        
        /// <remarks/>
        High,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Consumer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int consumerIdField;
        
        private int clientIdField;
        
        private int databaseIdField;
        
        private int appIdField;
        
        private int userIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ConsumerId {
            get {
                return this.consumerIdField;
            }
            set {
                this.consumerIdField = value;
                this.RaisePropertyChanged("ConsumerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int DatabaseId {
            get {
                return this.databaseIdField;
            }
            set {
                this.databaseIdField = value;
                this.RaisePropertyChanged("DatabaseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int AppId {
            get {
                return this.appIdField;
            }
            set {
                this.appIdField = value;
                this.RaisePropertyChanged("AppId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmh.plexxis.com")]
    public partial class Client : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int clientIdField;
        
        private string keyField;
        
        private string iPv4Field;
        
        private int portField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("ClientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IPv4 {
            get {
                return this.iPv4Field;
            }
            set {
                this.iPv4Field = value;
                this.RaisePropertyChanged("IPv4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
                this.RaisePropertyChanged("Port");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManagerSDKSoapChannel : Pmh.Manager.ManagementWebservice.ManagerSDKSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManagerSDKSoapClient : System.ServiceModel.ClientBase<Pmh.Manager.ManagementWebservice.ManagerSDKSoap>, Pmh.Manager.ManagementWebservice.ManagerSDKSoap {
        
        public ManagerSDKSoapClient() {
        }
        
        public ManagerSDKSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerSDKSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerSDKSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerSDKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetExternalIP() {
            return base.Channel.GetExternalIP();
        }
        
        public Pmh.Manager.ManagementWebservice.Command[] GetCommandRepo() {
            return base.Channel.GetCommandRepo();
        }
        
        public Pmh.Manager.ManagementWebservice.Client[] GetConnectionRepository() {
            return base.Channel.GetConnectionRepository();
        }
        
        public Pmh.Manager.ManagementWebservice.Consumer[] GetConsumerRepository() {
            return base.Channel.GetConsumerRepository();
        }
        
        public Pmh.Manager.ManagementWebservice.Log[] GetLogRepository() {
            return base.Channel.GetLogRepository();
        }
        
        public Pmh.Manager.ManagementWebservice.Response[] GetResponseRepository() {
            return base.Channel.GetResponseRepository();
        }
        
        public Pmh.Manager.ManagementWebservice.Log[] LogsGetAll() {
            return base.Channel.LogsGetAll();
        }
        
        public Pmh.Manager.ManagementWebservice.Result Query(string sql, object[] arguments) {
            return base.Channel.Query(sql, arguments);
        }
        
        public int NonQuery(string sql, object[] arguments) {
            return base.Channel.NonQuery(sql, arguments);
        }
        
        public void RetrieveCommand(int Id) {
            base.Channel.RetrieveCommand(Id);
        }
        
        public void ResetLogs() {
            base.Channel.ResetLogs();
        }
        
        public int AppAdd(string authKey, string title, string description, bool isClientCustomApp) {
            return base.Channel.AppAdd(authKey, title, description, isClientCustomApp);
        }
        
        public Pmh.Manager.ManagementWebservice.APPS AppRetrieve(int appId) {
            return base.Channel.AppRetrieve(appId);
        }
        
        public void AppRemove(int id) {
            base.Channel.AppRemove(id);
        }
        
        public Pmh.Manager.ManagementWebservice.APP_TABLES AppTableRetrieve(int appTableId) {
            return base.Channel.AppTableRetrieve(appTableId);
        }
        
        public int AppTableAdd(int appId, string name, string desc, int insert, int update, int delete, int select) {
            return base.Channel.AppTableAdd(appId, name, desc, insert, update, delete, select);
        }
        
        public void AppTableRemove(int id) {
            base.Channel.AppTableRemove(id);
        }
        
        public void AppTableColumnRemove(int id) {
            base.Channel.AppTableColumnRemove(id);
        }
        
        public int AppTableColumnAdd(int tabId, string nom, int seq, string type, int length, int prec, int scale, int nullable, int readOnly, int isLong, int isKey, string keyType, int unique, string desc) {
            return base.Channel.AppTableColumnAdd(tabId, nom, seq, type, length, prec, scale, nullable, readOnly, isLong, isKey, keyType, unique, desc);
        }
        
        public Pmh.Manager.ManagementWebservice.APP_TABLE_COLUMNS AppTableColumnRetrieve(int appTableColumnId) {
            return base.Channel.AppTableColumnRetrieve(appTableColumnId);
        }
        
        public Pmh.Manager.ManagementWebservice.CLIENTS ClientRetrieve(int clientId) {
            return base.Channel.ClientRetrieve(clientId);
        }
        
        public void ClientRemove(int id) {
            base.Channel.ClientRemove(id);
        }
        
        public int ClientAdd(int clientId, string desc, string key) {
            return base.Channel.ClientAdd(clientId, desc, key);
        }
        
        public int ClientAppsAdd(int appId, int clientId) {
            return base.Channel.ClientAppsAdd(appId, clientId);
        }
        
        public Pmh.Manager.ManagementWebservice.CLIENT_APPS ClientAppRetrieve(int clientAppId) {
            return base.Channel.ClientAppRetrieve(clientAppId);
        }
        
        public void ClientAppRemove(int id) {
            base.Channel.ClientAppRemove(id);
        }
    }
}
